services:
  fastapi-epg:
    build: .
    container_name: fastapi-epg
    ports:
      - "8000:8000"
    volumes:
      - ./Config:/app/Config
      - ./Data:/app/Data
    env_file:
      - Config/config.env
    restart: unless-stopped
